# Generated by Django 3.1.5 on 2021-02-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=40)),
                ('stock_name', models.CharField(max_length=20)),
                ('tag', models.CharField(max_length=20)),
                ('url', models.URLField()),
            ],
        ),
    ]
