# Generated by Django 3.1.5 on 2021-02-14 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210214_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='tags',
            new_name='tag',
        ),
    ]
