# Generated by Django 3.1.5 on 2021-02-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20210214_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='url',
            new_name='highUrl',
        ),
        migrations.AddField(
            model_name='picture',
            name='lowUrl',
            field=models.URLField(default='null'),
            preserve_default=False,
        ),
    ]
